linters-settings:
  goimports:
    local-prefixes: gitlab.com/soy-app/stock-api

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - prealloc
    - testpackage
    - exportloopref
    - thelper
    - gocognit
    - goimports
    - gofmt

run:
  go: 1.20
