version: '3.9'
services:
  template-backend:
    container_name: template-backend

    # Docker起動時、network 〇〇 not foundのエラーが出た場合、
    # docker network lsコマンドの実行で出てくる既存のdocker_networkの名前を
    # 以下のようnetwork_modeに設定する
    # network_mode: docker_default

    build:
      context: .
    volumes:
      - .:/app
      - C:\Users\djmaa\OneDrive\StockAnalysis\StockValueCSVByKabuplus:/app/stocks
    ports:
      - 80:80
    env_file: env.dev
    tty: true
    command: >
      ash -c "go run main.go"
