version: '3.9'
services:
  template-backend:
    container_name: template-backend

    # Docker起動時、network 〇〇 not foundのエラーが出た場合、
    # docker network lsコマンドの実行で出てくる既存のdocker_networkの名前を
    # 以下のようnetwork_modeに設定する
    # network_mode: docker_default

    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 80:80
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - ENV
      - AWS_ACCESS_KEY
      - AWS_PRIVATE_KEY
      - AWS_REGION
      - S3_BUCKET
      - SES_SENDER
      - POST_CODE_JP_TOKEN
      - FRONTEND_URL
    tty: true
    command: >
      ash -c "go run main.go"
