version: '3'
services:
  mysql-test:
    image: mysql:8.0.28
    container_name: template-mysql-test
    # platform: linux/x86_64
    ports:
      - 13306:13306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=template-test
      - MYSQL_USER=template-test
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
      - MYSQL_TCP_PORT=13306
    volumes:
      - template-mysql-test-data:/var/lib/mysql
      - ./mysql-test:/etc/mysql/conf.d

volumes:
  template-mysql-test-data:
