version: '3.9'

services:
  mysql-test:
    image: mysql:8.0.28
    container_name: template-mysql-test
    # platform: linux/x86_64
    ports:
      - 13306:13306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=template-test
      - MYSQL_USER=template-test
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
      - MYSQL_TCP_PORT=13306
    volumes:
      - template-mysql-test-data:/var/lib/mysql
      - ./mysql-test:/etc/mysql/conf.d

  template-backend-test:
    container_name: template-backend-test

    # Docker起動時、network 〇〇 not foundのエラーが出た場合、
    # docker network lsコマンドの実行で出てくる既存のdocker_networkの名前を
    # 以下のようnetwork_modeに設定する
    # network_mode: docker_default

    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 81:81
    env_file: env.test
    tty: true
    command: >
      ash -c "go run main.go"
